import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        inverse_surface: '#f6faf6',
        tertiary_dim: '#d23e42',
        surface_container_lowest: '#000000',
        outline_variant: '#444946',
        secondary_container: '#00687a',
        on_background: '#f9fdf9',
        on_secondary_fixed: '#003a45',
        primary_fixed: '#31fd71',
        primary_container: '#14f167',
        tertiary: '#ff706e',
        surface_dim: '#0a0f0d',
        background: '#0a0f0d',
        surface_container: '#151b18',
        secondary_fixed: '#6ae1ff',
        error_dim: '#d7383b',
        inverse_on_surface: '#515653',
        surface_container_low: '#0f1512',
        on_surface: '#f9fdf9',
        on_error_container: '#ffa8a3',
        secondary_dim: '#56d0ed',
        on_surface_variant: '#a7aca9',
        on_tertiary_fixed_variant: '#790012',
        on_primary_fixed_variant: '#006627',
        primary_dim: '#06ee65',
        surface_tint: '#46ff78',
        on_secondary_fixed_variant: '#005969',
        on_primary_fixed: '#004618',
        surface_variant: '#202724',
        surface: '#0a0f0d',
        error_container: '#9f0519',
        on_secondary: '#004d5b',
        on_tertiary_container: '#000000',
        inverse_primary: '#006e2a',
        on_primary_container: '#00531e',
        tertiary_fixed_dim: '#ff7a77',
        outline: '#717774',
        surface_container_highest: '#202724',
        on_primary: '#005d23',
        surface_bright: '#262e2b',
        primary_fixed_dim: '#06ee65',
        on_tertiary: '#490007',
        tertiary_fixed: '#ff928d',
        secondary_fixed_dim: '#59d3f0',
        secondary: '#66defc',
        primary: '#46ff78',
        surface_container_high: '#1a211e',
        error: '#ff716c',
        on_secondary_container: '#ecfaff',
        tertiary_container: '#dd4648',
        on_tertiary_fixed: '#3a0004',
        on_error: '#490006',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Space Grotesk', 'Fustat', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
        fustat: ['Fustat', 'sans-serif'],
        schibsted: ['Schibsted Grotesk', 'sans-serif'],
      },
    },
  },
  plugins: [],
};

export default config;
